# This is a basic workflow to help you get started with Actions

name: Publish package to npm registry

on: workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email "gkswlsrb95@gmail.com"
      - run: git config --global user.name "jinkyuhan"
      - run: yarn version --patch
      - run: git push origin main --tags
      - run: yarn && yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
